export const storeSelect = {
  id: true,
  name: true,
  status: true,
  email: true,
  description: true,
  phone: true,
  website: true,
  cnpj: true,
  ie: true,
  logoUrl: true,
  bannerUrl: true,
  createdAt: true,
  updatedAt: true,
  owner: {
    select: {
      id: true,
      name: true,
    },
  },
  category: true,
  addressStreet: true,
  addressNumber: true,
  addressComplement: true,
  addressNeighborhood: true,
  addressCity: true,
  addressState: true,
  addressZipCode: true,
  addressCountry: true,
}
